let randomNumber = Math.floor(Math.random() * 10) + 1;
console.log("Random number generated: " + randomNumber);

let guess = prompt("Guess a number between 1 and 10:");

while (guess != randomNumber) {
    guess = prompt("Incorrect. Please try again:");
}

alert("Correct! The random number was " + randomNumber);

// Project: Guess the Number
// Objective: To create a game where the user has to guess a random number generated by the computer.

// Steps:

// Generate a random number between 1 and 10.
const randomNumber = Math.floor(Math.random() * 10) + 1;
console.log("Random Number before loop: ",randomNumber)
// Ask the user to guess the number (using prompts).
let userInput = prompt('Guess a number between 1 and 10');
let toNumber = parseInt(userInput);
console.log('User Number', userInput);
console.log('parseInt: ', toNumber);

//while loop
// while(randomNumber != toNumber) { //not correct
//     //what to do?
//     //if the number is correct
//     userInput = prompt(`Incorrect. Guess again. Random Num: ${randomNumber}`);
//     //if the number is correct

// } console.log('Correct!')
// console.log('random number after loop: ', randomNumber);

// If the user's guess is correct, log "You guessed the correct number!" to the console.
// If the user's guess is incorrect, log "Sorry, that's not the correct number. Try again!" to the console and prompt the user to guess again.
// Repeat steps 3 and 4 until the user guesses the correct number.




// Project: Count the Vowels
// Objective: To create a program that counts the number of vowels in a given string.

// Steps:

// Ask the user to enter a string (using prompts).
// Convert the string to lowercase to make it case-insensitive.
// Create a variable to store the number of vowels and set it to 0.
// Loop through each character in the string.
// If the character is a vowel (a, e, i, o, or u), increment the vowel count by 1.
// Log the total vowel count to the console.





// Project: Palindrome Checker
// Objective: To create a program that checks whether a given string is a palindrome or not.

// Steps:

// Ask the user to enter a string (using prompts).
// Convert the string to lowercase to make it case-insensitive.
// Create a variable to store the reversed string and set it to an empty string.
// Loop through each character in the string, starting from the end.
// Append each character to the reversed string.
// Check if the reversed string is the same as the original string.
// Log whether the string is a palindrome or not to the console.






// Project: Rock, Paper, Scissors Game
// Objective: To create a program that plays the classic game of Rock, Paper, Scissors with the user.

// Steps:

// Create an array with the options: "rock", "paper", "scissors".
// Prompt the user to choose an option.
// Generate a random option for the computer.
// Compare the user's and computer's options and determine the winner.
// Log the winner and the choices to the console.